name: Node CI

on: [push, pull_request]

jobs:
  default:
    strategy:
      matrix:
        node: [10, 12]
        os: [macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Setup yarn
        run: |
          curl -o- -L https://yarnpkg.com/install.sh | bash
          export PATH="$HOME/.yarn/bin:$PATH"
      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Build, Lint and Test
        run: yarn run-s build lint test type-coverage
        env:
          EFF_NO_LINK_RULES: 'true'
          PARSER_NO_WATCH: 'true'
